### ISSUE TITLE
./dataset folder is missing

### ISSUE THREAD

**Issue by juliadietlmeier** [SJTU-Intelligent-Optics-Lab/Annotation-efficient-learning-for-OCT-segmentation#1]
Thank you for your very interesting work! Just noticed that the ./dataset folder is missing… 1) How can I use your pre-trained model on my custom dataset and 2) how can I train on my data?  Hope you will expand the README file. Thanks!

**Comment by SJTU-Intelligent-Optics-Lab** [comment]
Thanks for your question. We have upload "./dataset" folder, you can refer to the example of dataset on your own custom dataset for training and testing.
