### ISSUE TITLE
Weights download link is not working

### ISSUE THREAD

**Issue by juliadietlmeier** [SJTU-Intelligent-Optics-Lab/Annotation-efficient-learning-for-OCT-segmentation#2]
The download link you are providing can only be accessed from the internal campus network. Could you please provide a working link to download pre-trained weights from phase 1 and phase 2 models? Thank you.

**Comment by SJTU-Intelligent-Optics-Lab** [comment]
Thank you. We have updated a public download link of network weights in README.md. You can try it again.
